#!/usr/bin/env bash
set -euo pipefail

# Signs release archives and generates appcast.xml using Sparkle's
# generate_appcast — the official tool for building Sparkle update feeds.
#
# generate_appcast handles: EdDSA signing, architecture detection,
# version extraction from Info.plist, CDATA release notes, and merging
# new items into an existing appcast (preserving history).
#
# Usage: sign-and-appcast.sh <version>
# Requires: SPARKLE_PRIVATE_KEY env var, artifacts/ directory with ZIPs.

VERSION="${1:?Usage: sign-and-appcast.sh <version>}"

if [ -z "${SPARKLE_PRIVATE_KEY:-}" ]; then
  echo "❌ ERROR: SPARKLE_PRIVATE_KEY environment variable is not set"
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. Locate Sparkle tools
# ---------------------------------------------------------------------------
brew list --cask sparkle &>/dev/null || brew install --cask sparkle
SPARKLE_BIN="$(brew --caskroom)/sparkle/$(ls "$(brew --caskroom)/sparkle" | head -1)/bin"

# ---------------------------------------------------------------------------
# 2. Prepare staging directory
# ---------------------------------------------------------------------------
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT

# Copy archives
cp "artifacts/TablePro-${VERSION}-arm64.zip" "$STAGING/"
cp "artifacts/TablePro-${VERSION}-x86_64.zip" "$STAGING/"

# Copy existing appcast for history preservation
if [ -f appcast.xml ]; then
  cp appcast.xml "$STAGING/"
fi

# ---------------------------------------------------------------------------
# 3. Extract release notes from CHANGELOG.md → HTML
# ---------------------------------------------------------------------------
if [ -f release_notes.md ]; then
  NOTES=$(cat release_notes.md)
else
  NOTES=$(awk "/^## \\[${VERSION}\\]/{flag=1; next} /^## \\[/{flag=0} flag" CHANGELOG.md)
fi

if [ -z "$NOTES" ]; then
  RELEASE_HTML="<ul><li>Bug fixes and improvements</li></ul>"
else
  RELEASE_HTML=$(echo "$NOTES" | sed -E \
    -e 's/^### (.+)$/<h3>\1<\/h3>/' \
    -e 's/^- (.+)$/<li>\1<\/li>/' \
    -e '/^[[:space:]]*$/d' \
  | awk '
    /<li>/ {
      if (!in_list) { print "<ul>"; in_list=1 }
      print; next
    }
    {
      if (in_list) { print "</ul>"; in_list=0 }
      print
    }
    END { if (in_list) print "</ul>" }
  ')
fi

# Create HTML release notes files matching each archive name.
# generate_appcast picks up <archive-name>.html automatically.
for zip in "$STAGING"/TablePro-*.zip; do
  basename="${zip%.zip}"
  echo "$RELEASE_HTML" > "${basename}.html"
done

# ---------------------------------------------------------------------------
# 4. Run generate_appcast
# ---------------------------------------------------------------------------
DOWNLOAD_PREFIX="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-TableProApp/TablePro}/releases/download/v${VERSION}"

KEY_FILE=$(mktemp)
# Override trap to clean up both
trap 'rm -rf "$STAGING" "$KEY_FILE"' EXIT
echo "$SPARKLE_PRIVATE_KEY" > "$KEY_FILE"

"$SPARKLE_BIN/generate_appcast" \
  --ed-key-file "$KEY_FILE" \
  --download-url-prefix "$DOWNLOAD_PREFIX" \
  --embed-release-notes \
  --maximum-versions 0 \
  "$STAGING"

# ---------------------------------------------------------------------------
# 5. Copy result
# ---------------------------------------------------------------------------
mkdir -p appcast
cp "$STAGING/appcast.xml" appcast/appcast.xml

echo "✅ Appcast generated by generate_appcast:"
cat appcast/appcast.xml
